Eager error checking for 'RUNFILES_DIR' in the run template
I had a weird error occur during a `--sandbox_debug` session where instead of running the code it just crashed with

```
Error:   × Unable to run command:
  ├─▶ Unable to create base venv directory
  ╰─▶ Permission denied (os error 13)
```

```
4062937 stat("/.mutator.venv", 0x7fff2b5c0ed0) = -1 ENOENT (No such file or directory)
4062937 mkdir("/.mutator.venv", 0777)   = -1 EACCES (Permission denied)
4062937 stat("/.mutator.venv", 0x7fff2b5c0c20) = -1 ENOENT (No such file or directory)
4062937 write(2, "\33[31m  \342\224\234\342\224\200\342\226\266 \33[0mUnable to create base venv directory", 57) = 57
```

This came from not having the RUNFILES_DIR environment variable setup correctly. Which could be because bazel's `--show_subcommands` did not print it properly, I don't know precisely why and did not care to chase it down, I might do that later, or chalk it up to user error.

This script does have `set -u` so I expect it to just fail instead of proceeding with an empty variable expansion and bug chasing exercise but with this eager control I now have a more actionable error message.